CREATE DATABASE twitter0; 

USE twitter0 ;

CREATE TABLE IF NOT EXISTS User (
  `User_ID` CHAR(15) NOT NULL,
  `Password` CHAR(15) NOT NULL,
  `Email` CHAR(30) NULL,
  `Phone_number` CHAR(13) NULL,
  `Name` VARCHAR(20) NULL,
  PRIMARY KEY (`User_ID`));

CREATE TABLE IF NOT EXISTS Follow (
  `F_ID` INT NOT NULL AUTO_INCREMENT,
  `Following_ID` CHAR(15) NOT NULL,
  `Followed_ID` CHAR(15) NOT NULL,
  PRIMARY KEY (`F_ID`),
   FOREIGN KEY (`Following_ID`) REFERENCES User (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
   FOREIGN KEY (`Followed_ID`) REFERENCES User (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS Posts (
  `P_ID` INT NOT NULL AUTO_INCREMENT,
  `Text` TEXT NULL,
  `Writer_ID` CHAR(15) NOT NULL,
  `Date_time` DATETIME NOT NULL,
  PRIMARY KEY (`P_ID`),
      FOREIGN KEY (`Writer_ID`) REFERENCES User (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS Comments (
  `C_ID` INT NOT NULL AUTO_INCREMENT,
  `Text` TEXT NULL,
  `Commenter_ID` CHAR(15) NOT NULL,
  `P_ID` INT NOT NULL,
  `Parent_C_ID` INT NOT NULL DEFAULT 0,
  `Date_time` DATETIME NOT NULL,
  PRIMARY KEY (`C_ID`),
     FOREIGN KEY (`Commenter_ID`) REFERENCES User (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (`P_ID`) REFERENCES Posts (`P_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS Post_like (
  `PL_ID` INT NOT NULL AUTO_INCREMENT,
  `P_ID` INT NOT NULL,
  `User_ID` CHAR(15) NOT NULL,
   PRIMARY KEY (`PL_ID`),
     FOREIGN KEY (`P_ID`) REFERENCES Posts (`P_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (`User_ID`) REFERENCES User (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS Comment_like (
  `CL_ID` INT NOT NULL AUTO_INCREMENT,
  `C_ID` INT NOT NULL,
  `User_ID` CHAR(15) NOT NULL,
  PRIMARY KEY (`CL_ID`),
FOREIGN KEY (`C_ID`) REFERENCES Comments (`C_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
      FOREIGN KEY (`User_ID`)REFERENCES User (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS Direct_message (
  `DM_ID` INT NOT NULL AUTO_INCREMENT,
  `Text` TEXT NULL,
  `Sender_ID` CHAR(15) NOT NULL,
  `Receiver_ID` CHAR(15) NOT NULL,
  `Receiver_read` TINYINT(1) NOT NULL DEFAULT 0,
  `DATE_time` DATETIME NOT NULL,
  PRIMARY KEY (`DM_ID`),
    FOREIGN KEY (`Sender_ID`)REFERENCES User (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
      FOREIGN KEY (`Receiver_ID`)REFERENCES User (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS Repost_post (
  `RT_ID` INT NOT NULL AUTO_INCREMENT,
  `P_ID` INT NOT NULL,
  `User_ID` CHAR(15) NOT NULL,
  PRIMARY KEY (`RT_ID`),
    FOREIGN KEY (`P_ID`)REFERENCES Posts (`P_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
     FOREIGN KEY (`User_ID`)REFERENCES User (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS Repost_comment (
  `RT_ID` INT NOT NULL AUTO_INCREMENT,
  `C_ID` INT NOT NULL,
  `User_ID` CHAR(15) NOT NULL,
  PRIMARY KEY (`RT_ID`),
     FOREIGN KEY (`C_ID`)REFERENCES Comments (`C_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (`User_ID`) REFERENCES User (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

